export interface Module {
  n: number
  name: string
  mfr: string
  cat: string
  tags: string
}

export const MODULES: Module[] = [
  {n:1,name:"Hexinverter Mutant BD9",mfr:"Erica Synths",cat:"drum",tags:"Drum / Synth Voice"},
  {n:2,name:"Slew",mfr:"Befaco",cat:"modulation",tags:"Envelope Generator / Slew Limiter"},
  {n:3,name:"Light Rail",mfr:"After Later Audio",cat:"utility",tags:"Multiple / Utility"},
  {n:4,name:"lx-euclid",mfr:"AtoVproject",cat:"generative",tags:"Clock Generator / Clock Modulator"},
  {n:5,name:"AI024 X Filter",mfr:"AI Synthesis",cat:"filter",tags:"Filter"},
  {n:6,name:"Pet Rock",mfr:"Jonah Senzel",cat:"generative",tags:"Clock Modulator / Random"},
  {n:7,name:"Looping Delay",mfr:"4ms Company",cat:"fx",tags:"Delay / Looper / Digital"},
  {n:8,name:"ADDAC107",mfr:"ADDAC System",cat:"source",tags:"Synth Voice"},
  {n:9,name:"EDU Compressor",mfr:"Erica Synths",cat:"utility",tags:"Dynamics / VCA"},
  {n:10,name:"MEGA-TANG",mfr:"ALM Busy Circuits",cat:"utility",tags:"Stereo Mixer / VCA / Quad"},
  {n:11,name:"Pamela's PRO Workout",mfr:"ALM Busy Circuits",cat:"generative",tags:"Clock / LFO / Sequencer / Quantizer / Random"},
  {n:12,name:"Buildup&Drop Control unit",mfr:"Voltage Vibes",cat:"utility",tags:"Attenuator / CV Modulation / Switch"},
  {n:13,name:"Nautilus",mfr:"Qu-Bit Electronix",cat:"fx",tags:"Delay / Digital / Stereo / Effect"},
  {n:14,name:"LXR eurorack module",mfr:"Erica Synths",cat:"drum",tags:"Drum"},
  {n:15,name:"UniFX",mfr:"Boredbrain Music",cat:"utility",tags:"External / Utility / VCA"},
  {n:16,name:"Scrat",mfr:"Neutral Labs",cat:"filter",tags:"Distortion / Effect / Filter"},
  {n:17,name:"Valmorification",mfr:"Nonlinearcircuits",cat:"modulation",tags:"LFO / Waveshaper"},
  {n:18,name:"Marsupial",mfr:"SetonixSynth",cat:"filter",tags:"Filter / Dual Stereo"},
  {n:19,name:"MEX",mfr:"Befaco",cat:"utility",tags:"Expander"},
  {n:20,name:"Osiris",mfr:"Modbap Modular",cat:"source",tags:"Oscillator / Synth Voice / Digital"},
  {n:21,name:"AI001 Multiple Black",mfr:"AI Synthesis",cat:"utility",tags:"Multiple / Utility / Dual Stereo"},
  {n:22,name:"Hatz v2",mfr:"Patching Panda",cat:"drum",tags:"Drum / Dynamics / Noise / Synth Voice"},
  {n:23,name:"Babel",mfr:"New Systems Instruments",cat:"modulation",tags:"CV Modulation / Logic / Ring Modulator / Waveshaper"},
  {n:24,name:"DATA",mfr:"Mordax",cat:"utility",tags:"Clock / LFO / Oscillator / Tuner / Utility"},
  {n:25,name:"uGrids",mfr:"CalSynth",cat:"drum",tags:"Clock Generator / Random / Sequencer"},
  {n:26,name:"1036",mfr:"Behringer",cat:"modulation",tags:"Random / Sample and Hold / Dual Stereo"},
  {n:27,name:"ROTLFO",mfr:"Mobula Mobular",cat:"modulation",tags:"LFO"},
  {n:28,name:"M185 Sequencer",mfr:"RYK Modular",cat:"generative",tags:"Sequencer / MIDI / Clock / CV Modulation / Random"},
  {n:29,name:"Rample",mfr:"Squarp Instruments",cat:"drum",tags:"Sampling / Drum / MIDI"},
  {n:30,name:"MFOS Phaser",mfr:"MFOS",cat:"fx",tags:"Phase Shifter / Effect"},
  {n:31,name:"Mimetic Digitalis",mfr:"Noise Engineering",cat:"generative",tags:"CV Modulation / Random / Sequencer"},
  {n:32,name:"Univer Inter",mfr:"Noise Engineering",cat:"utility",tags:"MIDI"},
  {n:33,name:"Pachinko",mfr:"CalSynth",cat:"generative",tags:"Clock Generator / S&H / Sequencer / Random"},
  {n:34,name:"Aurora",mfr:"Qu-Bit Electronix",cat:"fx",tags:"Reverb / Pitch Shifter / Dual Stereo / Effect"},
  {n:35,name:"Data Bender",mfr:"Qu-Bit Electronix",cat:"fx",tags:"Digital / Distortion / Sampling / Stereo / Effect"},
  {n:36,name:"Surface",mfr:"Qu-Bit Electronix",cat:"source",tags:"Digital / Oscillator / Synth Voice / Dual Stereo"},
  {n:37,name:"Seismograf BD",mfr:"Frequency Central",cat:"drum",tags:"Drum"},
  {n:38,name:"Infinitely Maybe",mfr:"Frequency Central",cat:"modulation",tags:"Noise / Sample and Hold / Utility / Random"},
  {n:39,name:"Nostalgia 1.0",mfr:"Dreadbox",cat:"fx",tags:"Delay / Effect / External / LFO"},
  {n:40,name:"Quad Pingable LFO",mfr:"4ms Company",cat:"modulation",tags:"Clock Modulator / Digital / LFO / Quad"},
  {n:41,name:"Stereo Line Out 1U",mfr:"Intellijel",cat:"utility",tags:"Attenuator / Dual Stereo / External / Utility"},
  {n:42,name:"Outs",mfr:"Intellijel",cat:"utility",tags:"Attenuator / Dual Stereo / External / Utility"},
  {n:43,name:"AI010 Switching Attenuator",mfr:"AI Synthesis",cat:"utility",tags:"Attenuator / Multiple / Utility / Dual Stereo"},
  {n:44,name:"ADDAC103 T-Networks",mfr:"ADDAC System",cat:"drum",tags:"Drum / Quad / Filter"},
  {n:45,name:"Generate 3",mfr:"Joranalogue Audio Design",cat:"modulation",tags:"Oscillator / Function Generator"},
  {n:46,name:"Pico SEQ2",mfr:"Erica Synths",cat:"generative",tags:"Sequencer / Waveshaper"},
  {n:47,name:"Airstreamer",mfr:"Endorphin.es",cat:"modulation",tags:"Envelope Generator / LFO / Oscillator / CV Modulation / S&H / Slew Limiter"},
  {n:48,name:"Squawk Dirty To Me",mfr:"Endorphin.es",cat:"filter",tags:"Filter / VCA / Dual Stereo / Digital / Effect / Low Pass Gate"},
  {n:49,name:"Godspeed",mfr:"Endorphin.es",cat:"source",tags:"Oscillator / Tuner / Waveshaper / Noise"},
  {n:50,name:"Milky Way",mfr:"Endorphin.es",cat:"fx",tags:"Granular / Effect / VCA / Delay / Panning / Reverb"},
  {n:51,name:"ForeCastle",mfr:"Circuit Abbey",cat:"modulation",tags:"Envelope Generator / Quad"},
  {n:52,name:"Bloom",mfr:"Qu-Bit Electronix",cat:"generative",tags:"Clock Generator / Dual Stereo / Random / Sequencer"},
  {n:53,name:"µClouds SE",mfr:"Tall Dog",cat:"fx",tags:"Delay / Digital / Effect / Pitch Shifter / Sampling"},
  {n:54,name:"Steppy 1U",mfr:"Intellijel",cat:"generative",tags:"Digital / Sequencer / Clock Modulator / Quad / Random"},
  {n:55,name:"Muta Jovis",mfr:"Noise Engineering",cat:"utility",tags:"Multiple / Utility"},
  {n:56,name:"Clep Diaz",mfr:"Noise Engineering",cat:"generative",tags:"CV Modulation / LFO / Random / Sequencer"},
  {n:57,name:"Basimilus Iteritas Alter",mfr:"Noise Engineering",cat:"drum",tags:"Drum / Oscillator"},
  {n:58,name:"Dual FX",mfr:"Erica Synths",cat:"fx",tags:"Effect / Dual Stereo"},
  {n:59,name:"Subharmonicon",mfr:"Moog Music Inc.",cat:"source",tags:"Clock / Filter / Oscillator / Sequencer / Synth Voice / VCA"},
  {n:60,name:"SYSTEM 100 112 DUAL VCO",mfr:"Behringer",cat:"source",tags:"Dual Stereo / Oscillator"},
  {n:61,name:"uO_c",mfr:"Grayscale",cat:"generative",tags:"CV Modulation / Digital / Quad"},
  {n:62,name:"DFAM",mfr:"Moog Music Inc.",cat:"drum",tags:"Clock / Drum / Noise / Oscillator / Sequencer / Synth Voice"},
  {n:63,name:"Turing Machine Mk II",mfr:"Music Thing Modular",cat:"generative",tags:"Noise / Random / Sequencer"},
  {n:64,name:"Muxlicer",mfr:"Befaco",cat:"generative",tags:"Sequencer / Switch / Clock Generator"},
  {n:65,name:"Burst",mfr:"Befaco",cat:"modulation",tags:"Clock Generator / Clock Modulator / Frequency Divider / Random"},
  {n:66,name:"µBraids SE",mfr:"Tall Dog",cat:"source",tags:"Digital / Oscillator / Drum / Noise / Synth Voice"},
  {n:67,name:"DIY Polivoks VCO",mfr:"Erica Synths",cat:"source",tags:"Oscillator"},
  {n:68,name:"Buff Mult 1U",mfr:"Intellijel",cat:"utility",tags:"Multiple"},
  {n:69,name:"Quad VCA",mfr:"Intellijel",cat:"utility",tags:"Mixer / VCA / Quad"},
  {n:70,name:"Disting mk4",mfr:"Expert Sleepers",cat:"utility",tags:"Effect / Quantizer / Utility / LFO / Oscillator / Delay / Waveshaper"},
  {n:71,name:"A-101-2v",mfr:"Doepfer",cat:"filter",tags:"Low Pass Gate / VCA"},
  {n:72,name:"Irukandji Glitch Drum VCO",mfr:"Beast-Tek",cat:"drum",tags:"Drum / Oscillator / Digital / Synth Voice"},
  {n:73,name:"Pico DSP",mfr:"Erica Synths",cat:"fx",tags:"Delay / Distortion / Effect / Panning / Reverb"},
  {n:74,name:"Joystick",mfr:"horstronic",cat:"utility",tags:"Attenuator / Controller / Polarizer"},
  {n:75,name:"AI001 Multiple",mfr:"AI Synthesis",cat:"utility",tags:"Multiple"},
  {n:76,name:"A-156v",mfr:"Doepfer",cat:"utility",tags:"Dual Stereo / Quantizer"},
  {n:77,name:"Pico RND",mfr:"Erica Synths",cat:"modulation",tags:"LFO / Noise / Random"},
  {n:78,name:"Pico Trigger",mfr:"Erica Synths",cat:"modulation",tags:"Clock Generator / Controller / Function Generator"},
  {n:79,name:"USB Power 1U",mfr:"Intellijel",cat:"utility",tags:"Power"},
  {n:80,name:"Quadratt 1U",mfr:"Intellijel",cat:"utility",tags:"Attenuator / Mixer / Utility / CV Modulation"},
  {n:81,name:"ADDAC705",mfr:"ADDAC System",cat:"filter",tags:"Filter / Distortion"},
  {n:82,name:"Dual Atenuverter",mfr:"Befaco",cat:"utility",tags:"Attenuator / Utility / Mixer"},
  {n:83,name:"Mutable Instruments Frames",mfr:"Grayscale",cat:"utility",tags:"Attenuator / CV Modulation / Mixer / VCA"},
  {n:84,name:"MIDI 3",mfr:"Pittsburgh Modular",cat:"utility",tags:"Clock Generator / CV Modulation / MIDI / Dual Stereo"},
  {n:85,name:"RF Nomad",mfr:"Evaton Technologies",cat:"source",tags:"Oscillator / Noise"},
  {n:86,name:"A-151",mfr:"Doepfer",cat:"utility",tags:"Switch / Quad"},
  {n:87,name:"A-138b",mfr:"Doepfer",cat:"utility",tags:"Mixer / Quad"},
]

export const CAT_CLASS: Record<string, string> = {
  drum: 'cp-drum',
  generative: 'cp-generative',
  fx: 'cp-fx',
  modulation: 'cp-modulation',
  source: 'cp-source',
  utility: 'cp-utility',
  filter: 'cp-filter',
}

export const CAT_LABEL: Record<string, string> = {
  drum: 'Drum',
  generative: 'Generative',
  fx: 'Effect',
  modulation: 'Modulation',
  source: 'Source',
  utility: 'Utility',
  filter: 'Filter',
}
